name: Deploy backend

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн бекенда
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        run: echo Собирается билд бекенда (прогоняются юнит тетсы при сборке), формируется и публикуется Docker образ

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to stage/review app
        run: echo Просиходит деплой бекенда